# **Setup**

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_breast_cancer, load_diabetes
from sklearn.metrics import (accuracy_score, classification_report,
                             mean_squared_error, r2_score)

# **File Upload**

In [3]:
from google.colab import files
uploaded = files.upload()

Saving ml_dataset.csv to ml_dataset.csv

# **File Read**

In [4]:
df = pd.read_csv('ml_dataset.csv')
df.head()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,mean_fractal_dimension,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

# **Split Dataset**

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("ml_dataset.csv")

X = df.drop(columns=["target"])   # features
y = df["target"]                  # label

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# **Helper**

In [7]:
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, classification_report)
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

results = []   # every model's scores are saved here

def evaluate(name, y_pred, y_score=None):
    row = {
        "Model": name,
        "Accuracy":  accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall":    recall_score(y_test, y_pred),
        "F1 Score":  f1_score(y_test, y_pred),
        "ROC AUC":   roc_auc_score(y_test, y_score) if y_score is not None else None,
    }
    results.append(row)
    print(f"{name}  ->  Accuracy: {row['Accuracy']:.4f} | F1: {row['F1 Score']:.4f}")
    print(classification_report(y_test, y_pred))

# **Linear Regression**

In [8]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
score = model.predict(X_test)
pred = (score >= 0.5).astype(int)    # convert continuous output to class 0/1

evaluate("Linear Regression", pred, score)

Linear Regression  ->  Accuracy: 0.9561 | F1: 0.9660
              precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

# **Logistic Regression**

In [9]:
from sklearn.linear_model import LogisticRegression

model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("Logistic Regression", pred, model.predict_proba(X_test)[:, 1])

Logistic Regression  ->  Accuracy: 0.9825 | F1: 0.9861
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

# **Naive Bayes**

In [10]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("Naive Bayes", pred, model.predict_proba(X_test)[:, 1])

Naive Bayes  ->  Accuracy: 0.9386 | F1: 0.9517
              precision    recall  f1-score   support

           0       0.93      0.90      0.92        42
           1       0.95      0.96      0.95        72

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114

# **KNN**

In [11]:
from sklearn.neighbors import KNeighborsClassifier

model = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("KNN", pred, model.predict_proba(X_test)[:, 1])

KNN  ->  Accuracy: 0.9561 | F1: 0.9655
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114


# **SVM**

In [ ]:
from sklearn.svm import SVC

model = make_pipeline(StandardScaler(), SVC(kernel="rbf", probability=True, random_state=42))
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("SVM", pred, model.predict_proba(X_test)[:, 1])

SVM  ->  Accuracy: 0.9825 | F1: 0.9861
              precision    recall  f1-score   support

           0       0.98      0.98      0.98        42
           1       0.99      0.99      0.99        72

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

# **Decision Tree**

In [13]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("Decision Tree", pred, model.predict_proba(X_test)[:, 1])

Decision Tree  ->  Accuracy: 0.9211 | F1: 0.9362
              precision    recall  f1-score   support

           0       0.87      0.93      0.90        42
           1       0.96      0.92      0.94        72

    accuracy                           0.92       114
   macro avg       0.91      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114

# **Random Forest**

In [14]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("Random Forest", pred, model.predict_proba(X_test)[:, 1])

Random Forest  ->  Accuracy: 0.9561 | F1: 0.9655
              precision    recall  f1-score   support

           0       0.95      0.93      0.94        42
           1       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

# **Gradient Boosting**

In [15]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("Gradient Boosting", pred, model.predict_proba(X_test)[:, 1])

Gradient Boosting  ->  Accuracy: 0.9561 | F1: 0.9660
              precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

# **XGBoost**

In [16]:
from xgboost import XGBClassifier

model = XGBClassifier(n_estimators=200, learning_rate=0.1, max_depth=4,
                      eval_metric="logloss", random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("XGBoost", pred, model.predict_proba(X_test)[:, 1])

XGBoost  ->  Accuracy: 0.9474 | F1: 0.9589
              precision    recall  f1-score   support

           0       0.95      0.90      0.93        42
           1       0.95      0.97      0.96        72

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

# **LightGBM**

In [17]:
from lightgbm import LGBMClassifier

model = LGBMClassifier(n_estimators=200, learning_rate=0.1, random_state=42, verbose=-1)
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("LightGBM", pred, model.predict_proba(X_test)[:, 1])

LightGBM  ->  Accuracy: 0.9561 | F1: 0.9660
              precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

# **CatBoost**

In [18]:
!pip install catboost -q
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=300, learning_rate=0.1, depth=6,
                           verbose=0, random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

evaluate("CatBoost", pred, model.predict_proba(X_test)[:, 1])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 6.0 MB/s eta 0:00:00
CatBoost  ->  Accuracy: 0.9649 | F1: 0.9726
              precision    recall  f1-score   support

           0       0.97      0.93      0.95        42
           1       0.96      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

# **Final Comparison**

In [19]:
import pandas as pd

results_df = pd.DataFrame(results).sort_values("F1 Score", ascending=False)
results_df.round(4).reset_index(drop=True)

                  Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
0   Logistic Regression    0.9825     0.9861  0.9861    0.9861   0.9954
1                   SVM    0.9825     0.9861  0.9861    0.9861   0.9950
2              CatBoost    0.9649     0.9595  0.9861    0.9726   0.9970
3     Gradient Boosting    0.9561     0.9467  0.9861    0.9660   0.9897
4     Linear Regression    0.9561     0.9467  0.9861    0.9660   0.9924
5              LightGBM    0.9561     0.9467  0.9861    0.9660   0.9891
6                   KNN    0.9561     0.9589  0.9722    0.9655   0.9788
7         Random Forest    0.9561     0.9589  0.9722    0.9655   0.9931
8               XGBoost    0.9474     0.9459  0.9722    0.9589   0.9937
9           Naive Bayes    0.9386     0.9452  0.9583    0.9517   0.9878
10        Decision Tree    0.9211     0.9565  0.9167    0.9362   0.9163